/**
 * rage_pg.hpp — Skeleton class declarations
 * Rockstar Presents Table Tennis (Xbox 360, 2006)
 *
 * 1 classes — auto-generated by gen_headers_v3.py
 * Sources: rtti_vtable_map | vtable_layout_map | offset_cluster_map
 *          | debug_string_field_map | rtti_class_hierarchy
 *
 * TODO: fill return types, params, inheritance.
 *       Cross-ref recomp/structured_pass5_final/ for each method.
 */
#pragma once
#include <stdint.h>

// ── pgDictionary  [vtable @ 0x82027824] ──────────────────────────
struct pgDictionary {
    void**      vtable;           // +0x00

    // ── virtual methods ──
    virtual ~pgDictionary();                  // [0] @ 0x820c3658
};
