#!/usr/bin/env python3
"""
Explain the decompilation workflow: classes vs functions
"""

import json

# Load symbols to count functions
with open('/Users/Ozordi/Downloads/tt-decomp/config/434C4803/symbols.txt', 'r') as f:
    symbols = f.readlines()

# Count functions (lines with "size:")
total_functions = sum(1 for line in symbols if 'size:' in line)

# Load RTTI for class count
with open('/Users/Ozordi/Downloads/tt-decomp/config/434C4803/rtti_vtable_map.json', 'r') as f:
    rtti = json.load(f)

total_classes = len(rtti)

print("=" * 80)
print("DECOMPILATION WORKFLOW: CLASSES vs FUNCTIONS")
print("=" * 80)
print()

print("THE BIG PICTURE:")
print("-" * 80)
print(f"Total Classes (RTTI): {total_classes:,}")
print(f"Total Functions: {total_functions:,}")
print()

print("=" * 80)
print("PHASE 1: CLASS DEFINITIONS (Structure)")
print("=" * 80)
print()
print("Define the CLASS STRUCTURE (headers):")
print()
print("  class pongPlayer {")
print("  public:")
print("      virtual void Update();           // Declare method")
print("      virtual void ProcessInput();     // Declare method")
print("      virtual void Render();           // Declare method")
print("  ")
print("  private:")
print("      float m_position[3];             // Define data members")
print("      int m_score;")
print("      bool m_isActive;")
print("  };")
print()
print("This phase:")
print("  ✓ Defines class layout (member variables)")
print("  ✓ Declares method signatures")
print("  ✓ Establishes vtable structure")
print("  ✗ Does NOT implement the logic yet")
print()

print("=" * 80)
print("PHASE 2: FUNCTION IMPLEMENTATIONS (Logic)")
print("=" * 80)
print()
print("Implement the ACTUAL CODE for each method:")
print()
print("  void pongPlayer::Update() {")
print("      // THIS is where you decompile the assembly")
print("      if (m_isActive) {")
print("          m_position[0] += m_velocity[0] * deltaTime;")
print("          m_position[1] += m_velocity[1] * deltaTime;")
print("          CheckCollisions();")
print("      }")
print("  }")
print()
print("This phase:")
print("  ✓ Translates assembly to C++")
print("  ✓ Implements game logic")
print("  ✓ Handles control flow (if/while/for)")
print("  ✓ Makes function calls")
print()

print("=" * 80)
print("THE RELATIONSHIP")
print("=" * 80)
print()
print(f"1,715 classes → ~16,653 functions")
print()
print("Each class has multiple methods:")
print("  - pongPlayer: ~50 methods")
print("  - pongBall: ~30 methods")
print("  - grcDevice: ~100 methods")
print("  - etc.")
print()
print("Average: ~10 functions per class")
print()

print("=" * 80)
print("ITERATIVE APPROACH (Recommended)")
print("=" * 80)
print()
print("Don't separate phases completely. Instead:")
print()
print("1. Pick a class (e.g., pongPlayer)")
print("2. Define its structure (members + method signatures)")
print("3. Implement its critical methods (Update, Init, etc.)")
print("4. Move to next class")
print()
print("This way:")
print("  ✓ You can test as you go")
print("  ✓ Discover missing members during implementation")
print("  ✓ Refine class structure based on usage")
print("  ✓ Build incrementally toward menu boot")
print()

print("=" * 80)
print("CURRENT STATUS")
print("=" * 80)
print()
print(f"Classes defined: 14 / {total_classes:,} (0.82%)")
print(f"Functions implemented: 153 / {total_functions:,} (0.92%)")
print()
print("You're doing BOTH simultaneously (good approach!)")
print()

print("=" * 80)
print("WHAT YOU NEED FOR MENU BOOT")
print("=" * 80)
print()
print("You DON'T need all classes/functions. Focus on:")
print()
print("Critical Path (~2,500 functions across ~250 classes):")
print("  1. Memory allocators (rage::atAllocator, etc.)")
print("  2. Core RAGE systems (rage::datBase, rage::fiDevice)")
print("  3. Renderer bootstrap (grcDevice, grcTexture)")
print("  4. UI system (hud*, menu*)")
print("  5. Input handling (minimal)")
print()
print("The other 14,000+ functions are for:")
print("  - Gameplay (ball physics, AI, scoring)")
print("  - Advanced rendering (shaders, effects)")
print("  - Networking (multiplayer)")
print("  - Audio (sound effects, music)")
print("  - Achievements, replays, etc.")
print()
print("Stub those initially, implement later.")
print()

