// AUTO-GENERATED by phase4b_offset_cluster.py — DO NOT EDIT
// Originally produced field-offset clusters from PPC_LOAD/STORE frequency.
//
// AUDIT (2026-04-16): All 30 structs in this header now have authoritative
// definitions elsewhere in the tree. The placeholder layouts below were
// inferred from access patterns and are inferior to the hand-lifted versions
// in src/**.hpp. This header now contains only redirect comments so any
// straggler #include keeps compiling.
//
// If you need real layouts, include the canonical headers listed below.
// Do NOT re-add placeholder field_0xNNNN structs here.
#pragma once
#include <cstdint>

// ──────────────────────────────────────────────────────────────────────
// Authoritative locations (all forward decls + placeholder layouts removed):
//
//   atSingleton            → src/rage/memory.hpp           (also src/rage/misc/rage_at.hpp, include/rage/atSingleton.hpp)
//   audVoiceStream         → src/rage/audio/rage_audio.hpp (also include/audio/AudioControl.h)
//   crAnimDofFloat         → src/rage/animation/rage_anim.hpp
//   crAnimDofQuaternion    → src/rage/animation/rage_anim.hpp
//   crIKLimb               → src/rage/animation/rage_anim.hpp
//   fiAsciiTokenizer       → src/rage/misc/rage_fi.hpp
//   gmLogicSinglesMatch    → src/game/match/pong_match.hpp
//   hudFlashBase           → src/ui/hud.hpp
//   LocomotionStateAnim    → src/game/creature/pong_creature.hpp
//   msgMsgSink             → src/game/misc/pong_misc.hpp
//   phArticulatedCollider  → src/physics/ph_physics.hpp
//   phBoundBox             → src/physics/ph_physics.hpp
//   phBoundCapsule         → src/physics/ph_physics.hpp
//   phBoundComposite       → src/physics/ph_physics.hpp
//   phBoundGeometry        → src/physics/ph_physics.hpp
//   phInst                 → src/physics/ph_physics.hpp     (fwd decl: src/scene/sg_physical.hpp, include/scene/sg_physical.hpp, include/rage/types.h)
//   phJoint1Dof            → src/physics/ph_physics.hpp
//   phJoint3Dof            → src/physics/ph_physics.hpp
//   phLevelNew             → src/physics/ph_physics.hpp
//   phSimulator            → src/physics/ph_physics.hpp
//   pongBallInstance       → src/game/ball/pong_ball.hpp
//   pongCameraMgr          → src/game/camera/pong_camera.hpp
//   pongCreature           → src/game/creature/pong_creature.hpp
//   pongCreatureInst       → src/game/creature/pong_creature.hpp
//   pongNetMessageHolder   → src/game/network/pong_network.hpp
//   pongPlayer             → src/game/misc/pong_misc.hpp     (also src/game/player/pong_player.hpp)
//   pongShadowMap          → src/game/render/pong_render.hpp
//   pongTrainingDrill      → src/game/drill/pong_drill.hpp
//   SinglesNetworkClient   → src/game/network/pong_network.hpp (fwd decl: include/rage/snCreateMachine.hpp, include/game/pong_network_io.hpp)
//   sysMemSimpleAllocator  → src/rage/misc/rage_misc.hpp     (also include/rage/rage_misc.hpp)
//
// Historical offset cluster data (per-field PPC access frequencies) lives in
//   tools/offset_cluster_map.json
// Use that JSON if you need to compare cluster-inferred offsets against the
// hand-lifted struct layouts during further decomp passes.
// ──────────────────────────────────────────────────────────────────────
